#!/bin/bash

cd ../01_FASTA
mkdir ORIGINAL_FASTA_FILES
mv *output ../02_1TAXON_FASTA/
mv *fasta ../01_FASTA/ORIGINAL_FASTA_FILES/

cd ../02_1TAXON_FASTA
for f in *.fasta.output; do 
mv -- "$f" "${f%.fasta.output}.output"
done
